User_LJ = float(input("Enter amount of lemon juice (in cups):\n"))
User_water = float(input("Enter amount of water (in cups):\n"))
User_agave = float(input("Enter amount of agave nectar (in cups):\n"))
User_servings = float(input("How many servings does this make?"))
print("\n")
print("Lemonade ingredients - yields", '{:.2f}'.format(User_servings), "servings")
print('{:.2f}'.format(User_LJ), "cup(s) lemon juice")
print('{:.2f}'.format(User_water), "cup(s) water")
print('{:.2f}'.format(User_agave), "cup(s) agave nectar\n")
desired_serving = int(input("How many servings would you like to make?"))
print("\n")
print("Lemonade ingredients - yields", '{:.2f}'.format(desired_serving), "servings")
print('{:.2f}'.format(desired_serving/User_servings*User_LJ), "cup(s) lemon juice")
print('{:.2f}'.format(desired_serving/User_servings*User_water), "cup(s) water")
print('{:.2f}'.format(desired_serving/User_servings*User_agave), "cup(s) agave nectar\n")
print("Lemonade ingredients - yields", '{:.2f}'.format(desired_serving), "servings")
print('{:.2f}'.format(desired_serving/User_servings*User_LJ/16), "gallon(s) lemon juice")
print('{:.2f}'.format(desired_serving/User_servings*User_water/16), "gallon(s) water")
print(desired_serving/User_servings*User_agave/16, "gallon(s) agave nectar")
